# Generated by Django 4.0.4 on 2022-04-27 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_app', '0002_user_expiry_date_user_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expiry Date'),
        ),
    ]
